### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by neandrake** [comment]
Thanks for the pull request! What brings you to dicom-pipe?

**Comment by jayvdb** [comment]
I'm looking at DICOM parsers that have few dependencies than the [dicom crate](https://github.com/Enet4/dicom-rs).

**Comment by neandrake** [comment]
Excellent, welcome! If you have any questions or suggestions on improving documentation please mention and I’ll look to update, or questions on usage or comments on design. Minimal dependencies is a design goal of this crate. This crate is largely functional in the test dicom I’ve included, though I have yet to publish the crate to crates.io.

**Review by neandrake — APPROVED** [review]
Thanks for this!

**Pull request merged**
